name: Build Docs

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Checkout 🛎️
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          pip install -U sphinx-rtd-theme m2r2

      - name: Build Docs
        run: |
          PYTHONPATH=./ sphinx-build -b html ./docs/source/ ./public
          
          touch ./public/.nojekyll
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public